/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alex.oopmotorphpayrollsystem.GUI;

import alex.oopmotorphpayrollsystem.AccountAccess;
import alex.oopmotorphpayrollsystem.AttendanceRecord;
import alex.oopmotorphpayrollsystem.User;
import alex.oopmotorphpayrollsystem.HRPersonnel;
import alex.oopmotorphpayrollsystem.Employee;
import alex.oopmotorphpayrollsystem.GUI.AdminAddNewEmp;
import alex.oopmotorphpayrollsystem.GUI.ConfirmationPopUp;
import alex.oopmotorphpayrollsystem.SystemAdministrator;
import java.util.*;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex Resurreccion
 */
public class UserManagement extends javax.swing.JPanel {
    private AccountAccess account;
    private User user;
    private List<User> employees;
    
    /**
     * Creates new form HREmployeeManagement
     */
    public UserManagement() {
        initComponents();
    }
    
    public UserManagement(AccountAccess account, User user) {
        this.account = account;
        this.user = user;
        initComponents();
        loadEmployeeList();
        initListeners();
        if(user instanceof SystemAdministrator){
            employeeList.setText("User List");
            searchEmp.setText("Search User");
            addNew.setText("Add new user");
        }
    }
    
    private void initListeners(){
        EmpMngTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // If at least one row is selected, enable the button
                if (EmpMngTable.getSelectedRowCount() > 0) {
                    view.setEnabled(true);
                    edit.setEnabled(true);
                    delete.setEnabled(true);
                } else {
                    view.setEnabled(false);
                    edit.setEnabled(false);
                    delete.setEnabled(false);
                }
            }
        });
    }
    
    protected void loadEmployeeList(){
        if (user instanceof HRPersonnel || user instanceof SystemAdministrator) {
            // Cast user to HRPersonnel or SystemAdministrator, depending on the instance type
            if (user instanceof HRPersonnel) {
                HRPersonnel hrUser = (HRPersonnel) user;  // Cast to HRPersonnel
                if (searchEmpValue.getText().trim().isEmpty()) {
                    employees = hrUser.loadEmployeeList();  // No search term
                } else {
                    employees = hrUser.loadEmployeeList(searchEmpValue.getText());  // With search term
                }
            } else {
                SystemAdministrator adminUser = (SystemAdministrator) user;  // Cast to SystemAdministrator
                if (searchEmpValue.getText().trim().isEmpty()) {
                    employees = adminUser.loadEmployeeList();  // No search term
                } else {
                    employees = adminUser.loadEmployeeList(searchEmpValue.getText());  // With search term
                }
            }
        }
        DefaultTableModel model = (DefaultTableModel) EmpMngTable.getModel();
        model.setRowCount(0);
        for (User emp : employees) {
            Object data[] = {
                emp.getEmployeeID(),
                emp.getLastName(),
                emp.getFirstName(),
                emp.getSssNumber(),
                emp.getPhilhealthNumber(),
                emp.getTinNumber(),
                emp.getPagibigNumber()
            };

            // Add the row to the table model
            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeList = new javax.swing.JLabel();
        searchEmp = new javax.swing.JLabel();
        searchEmpValue = new javax.swing.JTextField();
        adminEmpMngSearchButton = new javax.swing.JButton();
        addNew = new javax.swing.JButton();
        view = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        EmpMngTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(860, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeList.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        employeeList.setForeground(new java.awt.Color(0, 0, 204));
        employeeList.setText("Employee List");
        add(employeeList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        searchEmp.setForeground(new java.awt.Color(0, 0, 0));
        searchEmp.setText("Search Employee");
        add(searchEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, -1));

        searchEmpValue.setBackground(new java.awt.Color(255, 255, 255));
        searchEmpValue.setForeground(new java.awt.Color(0, 0, 0));
        add(searchEmpValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 30));

        adminEmpMngSearchButton.setBackground(new java.awt.Color(255, 255, 255));
        adminEmpMngSearchButton.setForeground(new java.awt.Color(255, 255, 255));
        adminEmpMngSearchButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alex Resurreccion\\Documents\\NetBeansProjects\\OOPMotorPhPayrollSystem\\resources\\searchIcon.png")); // NOI18N
        adminEmpMngSearchButton.setFocusPainted(false);
        adminEmpMngSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEmpMngSearchButtonActionPerformed(evt);
            }
        });
        add(adminEmpMngSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 30, 30));

        addNew.setBackground(new java.awt.Color(0, 153, 51));
        addNew.setForeground(new java.awt.Color(255, 255, 255));
        addNew.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alex Resurreccion\\Documents\\NetBeansProjects\\OOPMotorPhPayrollSystem\\resources\\icons8-add-48.png")); // NOI18N
        addNew.setText("Add new employee");
        addNew.setBorder(null);
        addNew.setFocusPainted(false);
        addNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewActionPerformed(evt);
            }
        });
        add(addNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 190, 40));

        view.setBackground(new java.awt.Color(0, 0, 204));
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alex Resurreccion\\Documents\\NetBeansProjects\\OOPMotorPhPayrollSystem\\resources\\icons8-view-48.png")); // NOI18N
        view.setText("View");
        view.setBorder(null);
        view.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        view.setEnabled(false);
        view.setFocusPainted(false);
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMouseClicked(evt);
            }
        });
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 140, 30));

        edit.setBackground(new java.awt.Color(255, 102, 0));
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alex Resurreccion\\Documents\\NetBeansProjects\\OOPMotorPhPayrollSystem\\resources\\icons8-edit-48.png")); // NOI18N
        edit.setText("Edit");
        edit.setBorder(null);
        edit.setEnabled(false);
        edit.setFocusPainted(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 140, 30));

        delete.setBackground(new java.awt.Color(204, 0, 0));
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alex Resurreccion\\Documents\\NetBeansProjects\\OOPMotorPhPayrollSystem\\resources\\icons8-delete-48.png")); // NOI18N
        delete.setText("Delete");
        delete.setBorder(null);
        delete.setEnabled(false);
        delete.setFocusPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 140, 30));

        jScrollPane4.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane4MouseWheelMoved(evt);
            }
        });

        EmpMngTable.setAutoCreateRowSorter(true);
        EmpMngTable.setBackground(new java.awt.Color(255, 255, 255));
        EmpMngTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmpMngTable.setForeground(new java.awt.Color(0, 0, 0));
        EmpMngTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"10001", "Garcia", "Manuel III", "10/11/1983", "966-860-270", "Regular", "Chief Executive Officer"},
                {"10002", "Lim", "Antonio", "06/19/1988", "171-867-411", "Regular", "Chief Operating Officer"},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee no.", "Last Name", "First Name", "SSS no.", "Philhealth no.", "TIN no.", "PagIbig no."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmpMngTable.setGridColor(new java.awt.Color(153, 153, 153));
        EmpMngTable.setSelectionBackground(new java.awt.Color(0, 0, 153));
        EmpMngTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        EmpMngTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        EmpMngTable.setShowGrid(true);
        jScrollPane4.setViewportView(EmpMngTable);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 860, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void adminEmpMngSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEmpMngSearchButtonActionPerformed
//        this.employeeListSearch = searchEmpValue.getText();
        loadEmployeeList();
    }//GEN-LAST:event_adminEmpMngSearchButtonActionPerformed

    private void addNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewActionPerformed
        AdminAddNewEmp newEmpFrame = new AdminAddNewEmp(account, user, this);
        newEmpFrame.setVisible(true);
    }//GEN-LAST:event_addNewActionPerformed

    private void viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMouseClicked

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        int selectedRow = EmpMngTable.getSelectedRow();
        // get selectedRow employee and call to new frame
        if (selectedRow != -1) { // Ensure a row is selected
            User selectedUser = employees.get(selectedRow); // Get the corresponding employee
            AdminAddNewEmp newEmpFrame = new AdminAddNewEmp(
                    account, user, selectedUser, "View", this);
            newEmpFrame.setVisible(true);
        }
    }//GEN-LAST:event_viewActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int selectedRow = EmpMngTable.getSelectedRow();
        // get selectedRow employee and call to new frame
        if (selectedRow != -1) { // Ensure a row is selected
            User selectedUser = employees.get(selectedRow); // Get the corresponding employee
            AdminAddNewEmp newEmpFrame = new AdminAddNewEmp(
                    account, user, selectedUser, "Edit", this);
            newEmpFrame.setVisible(true);
        }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int selectedRow = EmpMngTable.getSelectedRow();
        // get selectedRow employee and call to new frame
        if (selectedRow != -1) { // Ensure a row is selected
            User selectedUser = employees.get(selectedRow);
            ConfirmationPopUp newEmpFrame = new ConfirmationPopUp(user, selectedUser, this);
            newEmpFrame.setVisible(true);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jScrollPane4MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane4MouseWheelMoved
        int rotation = evt.getWheelRotation();
                JScrollBar verticalScrollBar = jScrollPane4.getVerticalScrollBar();
                
                // Control the scroll speed here (higher value = faster scroll)
                int scrollAmount = rotation * 38;  // Adjust this multiplier for smoothness
                
                verticalScrollBar.setValue(verticalScrollBar.getValue() + scrollAmount);
    }//GEN-LAST:event_jScrollPane4MouseWheelMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmpMngTable;
    private javax.swing.JButton addNew;
    private javax.swing.JButton adminEmpMngSearchButton;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel employeeList;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel searchEmp;
    private javax.swing.JTextField searchEmpValue;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
