/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import models.AccountAccess;
import models.Employee;
import models.AttendanceRecord;
import models.HRPersonnel;
import models.User;
import dao.EmployeeDao;
import dao.HRPersonnelDao;
import java.util.List;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex Resurreccion
 */
public class Attendance extends javax.swing.JPanel {
    private AccountAccess account;
    private User user;
    /**
     * Creates new form Attendance
     */
    public Attendance() {
        initComponents();
    }

    
    /**
     *
     * @param account
     * @param user
     */
    public Attendance(AccountAccess account, User user) {
        this.account = account;
        this.user = user;
        initComponents();
        loadAttendance();
    }
    
    public void loadAttendance(){
        EmployeeDao employeeDao = new EmployeeDao();
        HRPersonnelDao hrPersonnelDao = new HRPersonnelDao();
        DefaultTableModel model = (DefaultTableModel) attendanceTable.getModel();
        model.setRowCount(0);
        List<AttendanceRecord> attendance;
        if(startDateValue.getDate() == null || endDateValue.getDate() == null){
            if(user instanceof HRPersonnel){
                attendance = hrPersonnelDao.loadAttendanceList();
            } else {
                attendance = employeeDao.loadAttendanceList(user.getEmployeeID());
            }
        } else {
            if(user instanceof HRPersonnel){
                attendance = hrPersonnelDao.loadAttendanceList(
                        user.getEmployeeID(), startDateValue.getDate(), endDateValue.getDate());
            } else {
                attendance = employeeDao.loadAttendanceList(
                        startDateValue.getDate(), endDateValue.getDate(), user.getEmployeeID());
            }
        }
        

        for (AttendanceRecord record : attendance) {
            Object data[] = {
                record.getEmployeeId(),
                record.getDate(),
                record.getTimeIn(),
                record.getTimeOut()};

            // Add the row to the table model
            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attendanceRecord = new javax.swing.JLabel();
        selectPeriod = new javax.swing.JLabel();
        startDateValue = new com.toedter.calendar.JDateChooser();
        endDateValue = new com.toedter.calendar.JDateChooser();
        startDate = new javax.swing.JLabel();
        endDate = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();
        EmpAttendanceSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(860, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendanceRecord.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        attendanceRecord.setForeground(new java.awt.Color(0, 0, 204));
        attendanceRecord.setText("Attendance Record");
        add(attendanceRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        selectPeriod.setForeground(new java.awt.Color(0, 0, 0));
        selectPeriod.setText("Select Period");
        add(selectPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        startDateValue.setBackground(new java.awt.Color(255, 255, 255));
        startDateValue.setForeground(new java.awt.Color(0, 0, 0));
        add(startDateValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 170, 30));

        endDateValue.setBackground(new java.awt.Color(255, 255, 255));
        endDateValue.setForeground(new java.awt.Color(51, 51, 51));
        add(endDateValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 170, 30));

        startDate.setForeground(new java.awt.Color(0, 0, 0));
        startDate.setText("Start Date");
        add(startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        endDate.setForeground(new java.awt.Color(0, 0, 0));
        endDate.setText("End Date");
        add(endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jScrollPane5.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane5MouseWheelMoved(evt);
            }
        });

        attendanceTable.setAutoCreateRowSorter(true);
        attendanceTable.setBackground(new java.awt.Color(255, 255, 255));
        attendanceTable.setForeground(new java.awt.Color(0, 0, 0));
        attendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"10001", "05/18/2023", "08:00", "15:00"},
                {"10001", "05/19/2023", "08:00", "15:00"},
                {"10001", "05/20/2023", "08:00", "15:00"},
                {"10001", "05/21/2023", "08:00", "15:00"},
                {"10001", "05/22/2023", "00:00", "00:00"},
                {"10001", "05/23/2023", "00:00", "00:00"},
                {"10001", "05/24/2023", "00:00", "00:00"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee no.", "Date", "Time in", "Time out"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        attendanceTable.setGridColor(new java.awt.Color(102, 102, 102));
        attendanceTable.setSelectionBackground(new java.awt.Color(0, 0, 153));
        attendanceTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        attendanceTable.setShowGrid(true);
        jScrollPane5.setViewportView(attendanceTable);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 860, 450));

        EmpAttendanceSearch.setBackground(new java.awt.Color(255, 255, 255));
        EmpAttendanceSearch.setForeground(new java.awt.Color(255, 255, 255));
        EmpAttendanceSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alex Resurreccion\\Documents\\NetBeansProjects\\OOPMotorPhPayrollSystem\\resources\\searchIcon.png")); // NOI18N
        EmpAttendanceSearch.setFocusPainted(false);
        EmpAttendanceSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpAttendanceSearchActionPerformed(evt);
            }
        });
        add(EmpAttendanceSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 60, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void EmpAttendanceSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpAttendanceSearchActionPerformed
        loadAttendance();
    }//GEN-LAST:event_EmpAttendanceSearchActionPerformed

    private void jScrollPane5MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane5MouseWheelMoved
         int rotation = evt.getWheelRotation();
                JScrollBar verticalScrollBar = jScrollPane5.getVerticalScrollBar();
                
                // Control the scroll speed here (higher value = faster scroll)
                int scrollAmount = rotation * 38;  // Adjust this multiplier for smoothness
                
                verticalScrollBar.setValue(verticalScrollBar.getValue() + scrollAmount);
    }//GEN-LAST:event_jScrollPane5MouseWheelMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmpAttendanceSearch;
    private javax.swing.JLabel attendanceRecord;
    private javax.swing.JTable attendanceTable;
    private javax.swing.JLabel endDate;
    private com.toedter.calendar.JDateChooser endDateValue;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel selectPeriod;
    private javax.swing.JLabel startDate;
    private com.toedter.calendar.JDateChooser startDateValue;
    // End of variables declaration//GEN-END:variables
}
