/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import models.User;
import models.HRPersonnel;
import models.Employee;
import models.SystemAdministrator;
import dao.HRPersonnelDao;
import dao.SystemAdministratorDao;
import java.util.*;

/**
 *
 * @author Alex Resurreccion
 */
public class ConfirmationPopUp extends javax.swing.JFrame {
    private User user;
    private User selectedUser;
    private UserManagement parentPanel;
    /**
     * Creates new form ConfirmationPopUp
     */
    public ConfirmationPopUp() {
        initComponents();
        messagePrompt.setVisible(false);
    }
    
    public ConfirmationPopUp(User user, User selectedUser, UserManagement parentPanel) {
        this.user = user;
        this.selectedUser = selectedUser;
        this.parentPanel = parentPanel;
        initComponents();
        messagePrompt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        deletePopup = new javax.swing.JPanel();
        deleteIcon = new javax.swing.JLabel();
        deleteEmp = new javax.swing.JLabel();
        confirmation = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        messagePrompt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 0, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deletePopup.setBackground(new java.awt.Color(255, 255, 255));
        deletePopup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-warning-48.png"))); // NOI18N
        deletePopup.add(deleteIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 70, 70));

        deleteEmp.setBackground(new java.awt.Color(255, 255, 255));
        deleteEmp.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        deleteEmp.setForeground(new java.awt.Color(0, 0, 0));
        deleteEmp.setText("Delete User?");
        deletePopup.add(deleteEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        confirmation.setBackground(new java.awt.Color(255, 255, 255));
        confirmation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        confirmation.setForeground(new java.awt.Color(0, 0, 0));
        confirmation.setText("Are you sure you want to delete User");
        deletePopup.add(confirmation, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 340, 50));

        confirm.setBackground(new java.awt.Color(204, 0, 0));
        confirm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("Confirm");
        confirm.setBorder(null);
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        deletePopup.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 110, 40));

        cancel.setBackground(new java.awt.Color(153, 153, 153));
        cancel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.setBorder(null);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        deletePopup.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 110, 40));

        messagePrompt.setBackground(new java.awt.Color(255, 255, 255));
        messagePrompt.setForeground(new java.awt.Color(0, 0, 255));
        messagePrompt.setText("Successfully deleted this user. Automatically closing in 3 seconds.");
        deletePopup.add(messagePrompt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 390, 40));

        kGradientPanel1.add(deletePopup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 450, 270));

        getContentPane().add(kGradientPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        boolean result = false;
        HRPersonnelDao hrPersonnelDao = new HRPersonnelDao();
        SystemAdministratorDao systemAdminDao = new SystemAdministratorDao();
        if(user instanceof HRPersonnel){
            result = hrPersonnelDao.deleteEmployee((Employee) selectedUser);
        } else {
            result = systemAdminDao.deleteEmployee(selectedUser);
        }
        
        if (result){
            messagePrompt.setVisible(true);
            confirm.setEnabled(false);
            Timer timer = new Timer();

            // Schedule a task to run dispose after 3 seconds.
            timer.schedule(new TimerTask() {
                @Override
                public void run() {
                    dispose();
                    parentPanel.loadEmployeeList();
                }
            }, 3000);
        }
    }//GEN-LAST:event_confirmActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmationPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmationPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmationPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmationPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmationPopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel confirmation;
    private javax.swing.JLabel deleteEmp;
    private javax.swing.JLabel deleteIcon;
    private javax.swing.JPanel deletePopup;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel messagePrompt;
    // End of variables declaration//GEN-END:variables
}
