/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import models.AccountAccess;
import models.Employee;
import models.SystemAdministrator;
import models.HRPersonnel;
import models.User;
import dao.HRPersonnelDao;
import dao.SystemAdministratorDao;
import java.util.List;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Alex Resurreccion
 */
public class Dashboard extends javax.swing.JPanel {
    private AccountAccess account;
    private User user;
    private List<User> newUsers;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }
    
    public Dashboard(AccountAccess account, User user) {
        this.account = account;
        this.user = user;
        initComponents();
        setDashboardInfo();
        setUserInfo();
        if(user instanceof SystemAdministrator){
            jLabel6.setText("Total Users");
            jLabel7.setText("New Users");
            employeeList.setText("New Users");
        }
        loadEmployeeList();
    }
    
    private void setUserInfo(){
        empNumberValue.setText(String.valueOf(user.getEmployeeID()));
        lastNameValue.setText(user.getLastName());
        positionLabelValue1.setText(user.getPosition());
        firstNameValue.setText(user.getFirstName());
        departmentLabelValue.setText(user.getDepartment());
        Date dateHired = user.getDateHired();
        SimpleDateFormat formatter = new SimpleDateFormat("MMMM d, yyyy");
        dateHiredLabelValue.setText(formatter.format(dateHired));
    }

    private void setDashboardInfo(){
        HRPersonnelDao hrPersonnelDao = new HRPersonnelDao();
        SystemAdministratorDao systemAdminDao = new SystemAdministratorDao();
        if(user instanceof HRPersonnel){
            List<Integer> dashboardInfo = hrPersonnelDao.loadDashboard();
            jLabel3.setText(Integer.toString(dashboardInfo.get(0)));
            jLabel9.setText("+" + Integer.toString(dashboardInfo.get(1)));
            
        } else {
            List<Integer> dashboardInfo = systemAdminDao.loadDashboard();
            jLabel3.setText(Integer.toString(dashboardInfo.get(0)));
            jLabel9.setText("+" + Integer.toString(dashboardInfo.get(1)));
            System.out.println(dashboardInfo.get(1));
            
        }
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM d, yyyy");
        SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm a");

        // Get the current date and time
        Date currentDate = new Date();

        // Format the date and time
        String formattedDate = dateFormat.format(currentDate);
        String formattedTime = timeFormat.format(currentDate);

        jLabel5.setText(formattedDate);  
        jLabel2.setText(formattedTime);  
    }
    
    protected void loadEmployeeList(){
        HRPersonnelDao hrPersonnelDao = new HRPersonnelDao();
        SystemAdministratorDao systemAdminDao = new SystemAdministratorDao();
        if (user instanceof HRPersonnel) {
            newUsers = hrPersonnelDao.loadNewEmployees();
        } else {
            newUsers = systemAdminDao.loadNewUsers();
        }
        DefaultTableModel model = (DefaultTableModel) EmpMngTable.getModel();
        model.setRowCount(0);
        for (User emp : newUsers) {
            Object data[] = {
                emp.getEmployeeID(),
                emp.getLastName(),
                emp.getFirstName(),
                emp.getSssNumber(),
                emp.getPhilhealthNumber(),
                emp.getTinNumber(),
                emp.getPagibigNumber()
            };

            // Add the row to the table model
            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        empPhoto = new javax.swing.JLabel();
        empNum = new javax.swing.JLabel();
        empNumberValue = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        lastNameValue = new javax.swing.JLabel();
        departmentLabel1 = new javax.swing.JLabel();
        positionLabelValue1 = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        firstNameValue = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        departmentLabelValue = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailLabelValue = new javax.swing.JLabel();
        dateHiredLabel = new javax.swing.JLabel();
        dateHiredLabelValue = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        EmpMngTable = new javax.swing.JTable();
        employeeList = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(860, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 0, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("05:04 PM");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetable.png"))); // NOI18N
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 90));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("January 1, 2025");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 150, 40));

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 270, 160));

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 0, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(153, 0, 255));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group.png"))); // NOI18N
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, -1));

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("34");
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 90, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Employees");
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 40));

        add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 220, 140));

        kGradientPanel3.setkEndColor(new java.awt.Color(0, 0, 204));
        kGradientPanel3.setkStartColor(new java.awt.Color(153, 0, 255));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("New Employee");
        kGradientPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new-employee.png"))); // NOI18N
        kGradientPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, 60));

        jLabel9.setFont(new java.awt.Font("SimSun-ExtB", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("+2");
        kGradientPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 100, 50));

        add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 220, 140));

        empPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employee Icon.png"))); // NOI18N
        empPhoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(empPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, 120));

        empNum.setForeground(new java.awt.Color(0, 0, 0));
        empNum.setText("Employee Number");
        add(empNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 126, -1, -1));

        empNumberValue.setForeground(new java.awt.Color(0, 0, 0));
        empNumberValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empNumberValue.setText("10000");
        empNumberValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        empNumberValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(empNumberValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 146, 100, 20));

        lastName.setForeground(new java.awt.Color(0, 0, 0));
        lastName.setText("Last Name");
        add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        lastNameValue.setForeground(new java.awt.Color(0, 0, 0));
        lastNameValue.setText("  Admin");
        lastNameValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lastNameValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lastNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, 26));

        departmentLabel1.setForeground(new java.awt.Color(0, 0, 0));
        departmentLabel1.setText("Position");
        add(departmentLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        positionLabelValue1.setForeground(new java.awt.Color(0, 0, 0));
        positionLabelValue1.setText("  Human Resourse");
        positionLabelValue1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        positionLabelValue1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(positionLabelValue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 140, 26));

        firstName.setForeground(new java.awt.Color(0, 0, 0));
        firstName.setText("First Name");
        add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        firstNameValue.setForeground(new java.awt.Color(0, 0, 0));
        firstNameValue.setText("  User");
        firstNameValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        firstNameValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(firstNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 140, 26));

        departmentLabel.setForeground(new java.awt.Color(0, 0, 0));
        departmentLabel.setText("Department");
        add(departmentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        departmentLabelValue.setForeground(new java.awt.Color(0, 0, 0));
        departmentLabelValue.setText("  Human Resource");
        departmentLabelValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        departmentLabelValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(departmentLabelValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 140, 26));

        emailLabel.setForeground(new java.awt.Color(0, 0, 0));
        emailLabel.setText("Email");
        add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        emailLabelValue.setForeground(new java.awt.Color(0, 0, 0));
        emailLabelValue.setText("  @example.com");
        emailLabelValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emailLabelValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(emailLabelValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 140, 26));

        dateHiredLabel.setForeground(new java.awt.Color(0, 0, 0));
        dateHiredLabel.setText("Date Hired");
        add(dateHiredLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        dateHiredLabelValue.setForeground(new java.awt.Color(0, 0, 0));
        dateHiredLabelValue.setText("  May 15, 2024");
        dateHiredLabelValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dateHiredLabelValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(dateHiredLabelValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 140, 26));

        jScrollPane4.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane4MouseWheelMoved(evt);
            }
        });

        EmpMngTable.setAutoCreateRowSorter(true);
        EmpMngTable.setBackground(new java.awt.Color(255, 255, 255));
        EmpMngTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmpMngTable.setForeground(new java.awt.Color(0, 0, 0));
        EmpMngTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"10001", "Garcia", "Manuel III", "10/11/1983", "966-860-270", "Regular", "Chief Executive Officer"},
                {"10002", "Lim", "Antonio", "06/19/1988", "171-867-411", "Regular", "Chief Operating Officer"},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee no.", "Last Name", "First Name", "SSS no.", "Philhealth no.", "TIN no.", "PagIbig no."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmpMngTable.setGridColor(new java.awt.Color(153, 153, 153));
        EmpMngTable.setSelectionBackground(new java.awt.Color(0, 0, 153));
        EmpMngTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        EmpMngTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        EmpMngTable.setShowGrid(true);
        jScrollPane4.setViewportView(EmpMngTable);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 860, 180));

        employeeList.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        employeeList.setForeground(new java.awt.Color(0, 0, 204));
        employeeList.setText("New Employee");
        add(employeeList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 30));

        jSeparator7.setForeground(new java.awt.Color(187, 187, 187));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 176, 860, 18));
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane4MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane4MouseWheelMoved
        int rotation = evt.getWheelRotation();
                JScrollBar verticalScrollBar = jScrollPane4.getVerticalScrollBar();
                
                // Control the scroll speed here (higher value = faster scroll)
                int scrollAmount = rotation * 38;  // Adjust this multiplier for smoothness
                
                verticalScrollBar.setValue(verticalScrollBar.getValue() + scrollAmount);
    }//GEN-LAST:event_jScrollPane4MouseWheelMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmpMngTable;
    private javax.swing.JLabel dateHiredLabel;
    private javax.swing.JLabel dateHiredLabelValue;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JLabel departmentLabel1;
    private javax.swing.JLabel departmentLabelValue;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabelValue;
    private javax.swing.JLabel empNum;
    private javax.swing.JLabel empNumberValue;
    private javax.swing.JLabel empPhoto;
    private javax.swing.JLabel employeeList;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel firstNameValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel lastNameValue;
    private javax.swing.JLabel positionLabelValue1;
    // End of variables declaration//GEN-END:variables
}
