/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.Timer;

/**
 *
 * @author Alex Resurreccion
 */
public class DownloadPDFPopUp extends javax.swing.JFrame {

    /**
     * Creates new form DownloadPDFPopUp
     */
    public DownloadPDFPopUp() {
        initComponents();
        messagePrompt.setVisible(false);
        jLabel1.setVisible(false);
        confirmation.setVisible(false);
        confirmation1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        deletePopup = new javax.swing.JPanel();
        deleteIcon = new javax.swing.JLabel();
        deleteEmp = new javax.swing.JLabel();
        confirmation = new javax.swing.JLabel();
        messagePrompt = new javax.swing.JLabel();
        confirmation1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 0, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deletePopup.setBackground(new java.awt.Color(255, 255, 255));
        deletePopup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (1).png"))); // NOI18N
        deletePopup.add(deleteIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 50));

        deleteEmp.setBackground(new java.awt.Color(255, 255, 255));
        deleteEmp.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        deleteEmp.setForeground(new java.awt.Color(0, 0, 0));
        deleteEmp.setText("Downloading...");
        deletePopup.add(deleteEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 310, -1));

        confirmation.setBackground(new java.awt.Color(255, 255, 255));
        confirmation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        confirmation.setForeground(new java.awt.Color(0, 0, 0));
        confirmation.setText("Filename as PDF file:");
        deletePopup.add(confirmation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 30));

        messagePrompt.setBackground(new java.awt.Color(255, 255, 255));
        messagePrompt.setForeground(new java.awt.Color(0, 0, 255));
        messagePrompt.setText("Successfully saved. Automatically closing in 5 seconds.");
        deletePopup.add(messagePrompt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 350, 40));

        confirmation1.setBackground(new java.awt.Color(255, 255, 255));
        confirmation1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        confirmation1.setForeground(new java.awt.Color(0, 0, 0));
        confirmation1.setText("[ report.pdf           ]");
        deletePopup.add(confirmation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 250, 30));

        jLabel1.setText("Go to computer's download folder for download pdf");
        deletePopup.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 300, -1));

        kGradientPanel1.add(deletePopup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 450, 270));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 440, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DownloadPDFPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DownloadPDFPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DownloadPDFPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DownloadPDFPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DownloadPDFPopUp().setVisible(true);
            }
        });
    }
    
    public void updateStatus(boolean success, String fileName) {
        if (success) {
            deleteEmp.setText("Download complete!");
            confirmation1.setText(fileName + ".pdf");
            messagePrompt.setVisible(true);
            jLabel1.setVisible(true);
            confirmation.setVisible(true);
            confirmation1.setVisible(true);
        } else {
            deleteEmp.setText("Download failed!");
            messagePrompt.setText(
                    "Something went wrong. Automatically closing in 5 seconds.");
            messagePrompt.setVisible(true);
        }
        revalidate();
        repaint();
        
        Timer timer = new Timer(5000, e -> dispose());
        timer.setRepeats(false);
        timer.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmation;
    private javax.swing.JLabel confirmation1;
    private javax.swing.JLabel deleteEmp;
    private javax.swing.JLabel deleteIcon;
    private javax.swing.JPanel deletePopup;
    private javax.swing.JLabel jLabel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel messagePrompt;
    // End of variables declaration//GEN-END:variables
}
