/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import models.AccountAccess;
import models.Address;
import models.Employee;
import models.Benefits;
import dao.EmployeeDao;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JScrollBar;

/**
 *
 * @author Alex Resurreccion
 */
public class EmpMyDetails extends javax.swing.JPanel {
    private AccountAccess account;
    private Employee user;
    /**
     * Creates new form EmpMyDetails
     */
    public EmpMyDetails() {
        initComponents();
    }
    
    public EmpMyDetails(AccountAccess account, Employee user) {
        this.account = account;
        this.user = user;
        initComponents();
        loadEmpDetails();
    }
    
    private void loadEmpDetails(){
        empIDValue.setText(String.valueOf(user.getEmployeeID()));
        empRoleValue.setSelectedItem(String.valueOf(account.getRole()));
        empLastNameValue.setText(user.getLastName());
        empFirstNameValue.setText(user.getFirstName());
        empBirthValue.setDate(user.getBirthday());
        empStatusValue.setText(user.getStatus());
        empDateHiredValue.setText("01/01/2025");
        empPositionValue.setText(user.getPosition());
        empImmediateSupValue.setText(user.getImmediateSupervisor());
        empPhoneNumValue.setText(user.getPhoneNumber());
        empPersonalEmailValue.setText("@example.motorph.com.ph");
        Address address = user.getAddress();
        addressStreetValue.setText(address.getStreet());
        addressBarangayValue.setText(address.getBarangay());
        addressCityValue.setText(address.getCity());
        addressProvinceValue.setText(address.getProvince());
        addressZipcodeValue.setText(address.getZipcode());
        
        Benefits benefit = ((Employee) user).getBenefits();
        empBasicSalaryValue.setText(Double.toString(benefit.getBasicSalary()));
        empGrossSemiValue.setText(Double.toString(benefit.getGrossSemiMonthlyRate()));
        empHourlyRateValue.setText(Double.toString(benefit.getHourlyRate()));
        empRiceSubValue.setText(Double.toString(benefit.getRiceSubsidy()));
        empPhoneAllowValue.setText(Double.toString(benefit.getPhoneAllowance()));
        empClothingAllowValue.setText(Double.toString(benefit.getClothingAllowance()));
        empSssValue.setText(user.getSssNumber());
        empTinValue.setText(user.getTinNumber());
        empPhilhealthValue.setText(user.getPhilhealthNumber());
        empPagIbigValue.setText(user.getPagibigNumber());
        
        // add more field settext
        empSuccessUpdated.setVisible(false);

//        add more warning setvisible
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        empImmediateSupValue = new javax.swing.JTextField();
        empImmediateSup = new javax.swing.JLabel();
        empLastNameValue = new javax.swing.JTextField();
        empBirth = new javax.swing.JLabel();
        empPayInfo = new javax.swing.JLabel();
        empFirstName = new javax.swing.JLabel();
        empFirstNameValue = new javax.swing.JTextField();
        empPersonalEmail = new javax.swing.JLabel();
        empPersonalEmailValue = new javax.swing.JTextField();
        empID = new javax.swing.JLabel();
        empDateHired = new javax.swing.JLabel();
        empDateHiredValue = new javax.swing.JTextField();
        empStatusValue = new javax.swing.JTextField();
        empPositionValue = new javax.swing.JTextField();
        empAddInfo = new javax.swing.JLabel();
        empLastName = new javax.swing.JLabel();
        empIDValue = new javax.swing.JTextField();
        empContact = new javax.swing.JLabel();
        empStatus = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        empPhoneNum = new javax.swing.JLabel();
        empHourlyRateValue = new javax.swing.JTextField();
        empAllow = new javax.swing.JLabel();
        empHourlyRate = new javax.swing.JLabel();
        empClothingAllow = new javax.swing.JLabel();
        empClothingAllowValue = new javax.swing.JTextField();
        empGrossSemi = new javax.swing.JLabel();
        empGrossSemiValue = new javax.swing.JTextField();
        empBenefits = new javax.swing.JLabel();
        empPhilhealth = new javax.swing.JLabel();
        empRiceSub = new javax.swing.JLabel();
        empPhoneAllow = new javax.swing.JLabel();
        empPhilhealthValue = new javax.swing.JTextField();
        empRiceSubValue = new javax.swing.JTextField();
        empPhoneAllowValue = new javax.swing.JTextField();
        empSalary = new javax.swing.JLabel();
        empBasicSalaryValue = new javax.swing.JTextField();
        empBasicSalary = new javax.swing.JLabel();
        empPagIbig = new javax.swing.JLabel();
        empPagIbigValue = new javax.swing.JTextField();
        empSss = new javax.swing.JLabel();
        empTin = new javax.swing.JLabel();
        empSssValue = new javax.swing.JTextField();
        empTinValue = new javax.swing.JTextField();
        empSubmitButton = new javax.swing.JButton();
        empPosition = new javax.swing.JLabel();
        empRoleValue = new javax.swing.JComboBox<>();
        empBirthValue = new com.toedter.calendar.JDateChooser();
        empSuccessUpdated = new javax.swing.JLabel();
        empUserRole = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        empInfoForm = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        empPhoneNumValue = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        addressStreet = new javax.swing.JLabel();
        addressStreetValue = new javax.swing.JTextField();
        addressProvince = new javax.swing.JLabel();
        addressProvinceValue = new javax.swing.JTextField();
        addressBarangay = new javax.swing.JLabel();
        addressBarangayValue = new javax.swing.JTextField();
        addressZipcode = new javax.swing.JLabel();
        addressZipcodeValue = new javax.swing.JTextField();
        addressCity = new javax.swing.JLabel();
        addressCityValue = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(860, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane1MouseWheelMoved(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 1360));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empImmediateSupValue.setEditable(false);
        empImmediateSupValue.setBackground(new java.awt.Color(227, 227, 227));
        empImmediateSupValue.setForeground(new java.awt.Color(0, 0, 0));
        empImmediateSupValue.setToolTipText("");
        empImmediateSupValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empImmediateSupValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empImmediateSupValueActionPerformed(evt);
            }
        });
        jPanel3.add(empImmediateSupValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 190, 30));

        empImmediateSup.setBackground(new java.awt.Color(255, 255, 255));
        empImmediateSup.setForeground(new java.awt.Color(0, 0, 0));
        empImmediateSup.setText(" Immediate Supervisor");
        empImmediateSup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empImmediateSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 190, 30));

        empLastNameValue.setEditable(false);
        empLastNameValue.setBackground(new java.awt.Color(227, 227, 227));
        empLastNameValue.setForeground(new java.awt.Color(0, 0, 0));
        empLastNameValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empLastNameValue.setVerifyInputWhenFocusTarget(false);
        empLastNameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empLastNameValueActionPerformed(evt);
            }
        });
        jPanel3.add(empLastNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 190, 30));

        empBirth.setBackground(new java.awt.Color(255, 255, 255));
        empBirth.setForeground(new java.awt.Color(0, 0, 0));
        empBirth.setText(" Date of Brith");
        empBirth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 190, 30));

        empPayInfo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        empPayInfo.setForeground(new java.awt.Color(0, 0, 204));
        empPayInfo.setText("PAYROLL INFORMATION");
        jPanel3.add(empPayInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, -1, 30));

        empFirstName.setBackground(new java.awt.Color(255, 255, 255));
        empFirstName.setForeground(new java.awt.Color(0, 0, 0));
        empFirstName.setText(" First Name ");
        empFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 190, 30));

        empFirstNameValue.setEditable(false);
        empFirstNameValue.setBackground(new java.awt.Color(227, 227, 227));
        empFirstNameValue.setForeground(new java.awt.Color(0, 0, 0));
        empFirstNameValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empFirstNameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empFirstNameValueActionPerformed(evt);
            }
        });
        jPanel3.add(empFirstNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 190, 30));

        empPersonalEmail.setBackground(new java.awt.Color(255, 255, 255));
        empPersonalEmail.setForeground(new java.awt.Color(0, 0, 0));
        empPersonalEmail.setText(" Personal Email");
        empPersonalEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empPersonalEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 190, 30));

        empPersonalEmailValue.setBackground(new java.awt.Color(255, 255, 255));
        empPersonalEmailValue.setForeground(new java.awt.Color(0, 0, 0));
        empPersonalEmailValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empPersonalEmailValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPersonalEmailValueActionPerformed(evt);
            }
        });
        jPanel3.add(empPersonalEmailValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 190, 30));

        empID.setBackground(new java.awt.Color(255, 255, 255));
        empID.setForeground(new java.awt.Color(0, 0, 0));
        empID.setText("Employee no.");
        empID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, 30));

        empDateHired.setBackground(new java.awt.Color(255, 255, 255));
        empDateHired.setForeground(new java.awt.Color(0, 0, 0));
        empDateHired.setText(" Date hired");
        empDateHired.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empDateHired, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, 30));

        empDateHiredValue.setEditable(false);
        empDateHiredValue.setBackground(new java.awt.Color(227, 227, 227));
        empDateHiredValue.setForeground(new java.awt.Color(0, 0, 0));
        empDateHiredValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empDateHiredValue.setEnabled(false);
        empDateHiredValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empDateHiredValueActionPerformed(evt);
            }
        });
        jPanel3.add(empDateHiredValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 190, 30));

        empStatusValue.setEditable(false);
        empStatusValue.setBackground(new java.awt.Color(227, 227, 227));
        empStatusValue.setForeground(new java.awt.Color(0, 0, 0));
        empStatusValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empStatusValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empStatusValueActionPerformed(evt);
            }
        });
        jPanel3.add(empStatusValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 190, 30));

        empPositionValue.setEditable(false);
        empPositionValue.setBackground(new java.awt.Color(227, 227, 227));
        empPositionValue.setForeground(new java.awt.Color(0, 0, 0));
        empPositionValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empPositionValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPositionValueActionPerformed(evt);
            }
        });
        jPanel3.add(empPositionValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 190, 30));

        empAddInfo.setBackground(new java.awt.Color(255, 255, 255));
        empAddInfo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        empAddInfo.setForeground(new java.awt.Color(0, 0, 204));
        empAddInfo.setText("ADDRESS INFORMATION");
        jPanel3.add(empAddInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, 30));

        empLastName.setBackground(new java.awt.Color(255, 255, 255));
        empLastName.setForeground(new java.awt.Color(0, 0, 0));
        empLastName.setText(" Last Name ");
        empLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 30));

        empIDValue.setEditable(false);
        empIDValue.setBackground(new java.awt.Color(227, 227, 227));
        empIDValue.setForeground(new java.awt.Color(0, 0, 0));
        empIDValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empIDValue.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        empIDValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIDValueActionPerformed(evt);
            }
        });
        jPanel3.add(empIDValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 190, 30));

        empContact.setBackground(new java.awt.Color(255, 255, 255));
        empContact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        empContact.setForeground(new java.awt.Color(0, 0, 204));
        empContact.setText("CONTACT INFORMATION");
        jPanel3.add(empContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 30));

        empStatus.setBackground(new java.awt.Color(255, 255, 255));
        empStatus.setForeground(new java.awt.Color(0, 0, 0));
        empStatus.setText(" Status");
        empStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 190, 30));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1020, 730, 20));

        empPhoneNum.setBackground(new java.awt.Color(255, 255, 255));
        empPhoneNum.setForeground(new java.awt.Color(0, 0, 0));
        empPhoneNum.setText(" Phone Number");
        empPhoneNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 190, 30));

        empHourlyRateValue.setEditable(false);
        empHourlyRateValue.setBackground(new java.awt.Color(227, 227, 227));
        empHourlyRateValue.setForeground(new java.awt.Color(0, 0, 0));
        empHourlyRateValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empHourlyRateValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empHourlyRateValueActionPerformed(evt);
            }
        });
        jPanel3.add(empHourlyRateValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 810, 200, 30));

        empAllow.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        empAllow.setForeground(new java.awt.Color(0, 0, 204));
        empAllow.setText("Allowances");
        jPanel3.add(empAllow, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 880, 100, 30));

        empHourlyRate.setForeground(new java.awt.Color(0, 0, 0));
        empHourlyRate.setText(" Hourly Rate");
        empHourlyRate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empHourlyRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 780, 200, 30));

        empClothingAllow.setBackground(new java.awt.Color(255, 255, 255));
        empClothingAllow.setForeground(new java.awt.Color(0, 0, 0));
        empClothingAllow.setText(" Clothing Allowance");
        empClothingAllow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empClothingAllow, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 920, 200, 30));

        empClothingAllowValue.setEditable(false);
        empClothingAllowValue.setBackground(new java.awt.Color(227, 227, 227));
        empClothingAllowValue.setForeground(new java.awt.Color(0, 0, 0));
        empClothingAllowValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empClothingAllowValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empClothingAllowValueActionPerformed(evt);
            }
        });
        jPanel3.add(empClothingAllowValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 950, 200, 30));

        empGrossSemi.setForeground(new java.awt.Color(0, 0, 0));
        empGrossSemi.setText(" Gross Semi-monthly Rate");
        empGrossSemi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empGrossSemi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 780, 200, 30));

        empGrossSemiValue.setEditable(false);
        empGrossSemiValue.setBackground(new java.awt.Color(227, 227, 227));
        empGrossSemiValue.setForeground(new java.awt.Color(0, 0, 0));
        empGrossSemiValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empGrossSemiValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empGrossSemiValueActionPerformed(evt);
            }
        });
        jPanel3.add(empGrossSemiValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 810, 200, 30));

        empBenefits.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        empBenefits.setForeground(new java.awt.Color(0, 0, 204));
        empBenefits.setText("Benefits");
        jPanel3.add(empBenefits, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1030, 90, 30));

        empPhilhealth.setBackground(new java.awt.Color(255, 255, 255));
        empPhilhealth.setForeground(new java.awt.Color(0, 0, 0));
        empPhilhealth.setText(" Philhealth number");
        empPhilhealth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empPhilhealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1130, 190, 30));

        empRiceSub.setBackground(new java.awt.Color(255, 255, 255));
        empRiceSub.setForeground(new java.awt.Color(0, 0, 0));
        empRiceSub.setText(" Rice Subsidy");
        empRiceSub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empRiceSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 920, 200, 30));

        empPhoneAllow.setBackground(new java.awt.Color(255, 255, 255));
        empPhoneAllow.setForeground(new java.awt.Color(0, 0, 0));
        empPhoneAllow.setText(" Phone Allowance");
        empPhoneAllow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empPhoneAllow, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 920, 200, 30));

        empPhilhealthValue.setEditable(false);
        empPhilhealthValue.setBackground(new java.awt.Color(227, 227, 227));
        empPhilhealthValue.setForeground(new java.awt.Color(0, 0, 0));
        empPhilhealthValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empPhilhealthValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPhilhealthValueActionPerformed(evt);
            }
        });
        jPanel3.add(empPhilhealthValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1130, 190, 30));

        empRiceSubValue.setEditable(false);
        empRiceSubValue.setBackground(new java.awt.Color(227, 227, 227));
        empRiceSubValue.setForeground(new java.awt.Color(0, 0, 0));
        empRiceSubValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empRiceSubValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empRiceSubValueActionPerformed(evt);
            }
        });
        jPanel3.add(empRiceSubValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 950, 200, 30));

        empPhoneAllowValue.setEditable(false);
        empPhoneAllowValue.setBackground(new java.awt.Color(227, 227, 227));
        empPhoneAllowValue.setForeground(new java.awt.Color(0, 0, 0));
        empPhoneAllowValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empPhoneAllowValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPhoneAllowValueActionPerformed(evt);
            }
        });
        jPanel3.add(empPhoneAllowValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 950, 200, 30));

        empSalary.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        empSalary.setForeground(new java.awt.Color(0, 0, 204));
        empSalary.setText("Salary Rate");
        jPanel3.add(empSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 740, 120, 30));

        empBasicSalaryValue.setEditable(false);
        empBasicSalaryValue.setBackground(new java.awt.Color(227, 227, 227));
        empBasicSalaryValue.setForeground(new java.awt.Color(0, 0, 0));
        empBasicSalaryValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empBasicSalaryValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empBasicSalaryValueActionPerformed(evt);
            }
        });
        jPanel3.add(empBasicSalaryValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 810, 200, 30));

        empBasicSalary.setForeground(new java.awt.Color(0, 0, 0));
        empBasicSalary.setText(" Basic Salary");
        empBasicSalary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 780, 200, 30));

        empPagIbig.setBackground(new java.awt.Color(255, 255, 255));
        empPagIbig.setForeground(new java.awt.Color(0, 0, 0));
        empPagIbig.setText(" Pag-ibig number");
        empPagIbig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empPagIbig, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1130, 190, 30));

        empPagIbigValue.setEditable(false);
        empPagIbigValue.setBackground(new java.awt.Color(227, 227, 227));
        empPagIbigValue.setForeground(new java.awt.Color(0, 0, 0));
        empPagIbigValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empPagIbigValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPagIbigValueActionPerformed(evt);
            }
        });
        jPanel3.add(empPagIbigValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 1130, 190, 30));

        empSss.setBackground(new java.awt.Color(255, 255, 255));
        empSss.setForeground(new java.awt.Color(0, 0, 0));
        empSss.setText(" SSS number");
        empSss.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empSss, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1070, 190, 30));

        empTin.setBackground(new java.awt.Color(255, 255, 255));
        empTin.setForeground(new java.awt.Color(0, 0, 0));
        empTin.setText(" TIN number");
        empTin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1070, 190, 30));

        empSssValue.setEditable(false);
        empSssValue.setBackground(new java.awt.Color(227, 227, 227));
        empSssValue.setForeground(new java.awt.Color(0, 0, 0));
        empSssValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empSssValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSssValueActionPerformed(evt);
            }
        });
        jPanel3.add(empSssValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1070, 190, 30));

        empTinValue.setEditable(false);
        empTinValue.setBackground(new java.awt.Color(227, 227, 227));
        empTinValue.setForeground(new java.awt.Color(0, 0, 0));
        empTinValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empTinValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empTinValueActionPerformed(evt);
            }
        });
        jPanel3.add(empTinValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 1070, 190, 30));

        empSubmitButton.setBackground(new java.awt.Color(255, 255, 255));
        empSubmitButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        empSubmitButton.setForeground(new java.awt.Color(0, 0, 255));
        empSubmitButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alex Resurreccion\\Documents\\NetBeansProjects\\OOPMotorPhPayrollSystem\\resources\\send.png")); // NOI18N
        empSubmitButton.setText("Submit");
        empSubmitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        empSubmitButton.setFocusPainted(false);
        empSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSubmitButtonActionPerformed(evt);
            }
        });
        jPanel3.add(empSubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1230, 160, 50));

        empPosition.setBackground(new java.awt.Color(255, 255, 255));
        empPosition.setForeground(new java.awt.Color(0, 0, 0));
        empPosition.setText(" Position");
        empPosition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 190, 30));

        empRoleValue.setBackground(new java.awt.Color(227, 227, 227));
        empRoleValue.setForeground(new java.awt.Color(0, 0, 0));
        empRoleValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "System Administrator", "HR Personnel", "Employee" }));
        empRoleValue.setLightWeightPopupEnabled(false);
        empRoleValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empRoleValueActionPerformed(evt);
            }
        });
        jPanel3.add(empRoleValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 190, 30));

        empBirthValue.setBackground(new java.awt.Color(227, 227, 227));
        empBirthValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empBirthValue.setForeground(new java.awt.Color(0, 0, 0));
        empBirthValue.setDateFormatString("MM/dd/yyyy");
        empBirthValue.setEnabled(false);
        jPanel3.add(empBirthValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 190, 30));

        empSuccessUpdated.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        empSuccessUpdated.setForeground(new java.awt.Color(0, 0, 255));
        empSuccessUpdated.setText("Successfully updated personal information. ");
        jPanel3.add(empSuccessUpdated, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1300, -1, 20));

        empUserRole.setBackground(new java.awt.Color(255, 255, 255));
        empUserRole.setForeground(new java.awt.Color(0, 0, 0));
        empUserRole.setText(" User type");
        empUserRole.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(empUserRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 190, 30));

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 0, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(153, 0, 204));
        jPanel3.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1370, 810, 20));

        empInfoForm.setBackground(new java.awt.Color(255, 255, 255));
        empInfoForm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        empInfoForm.setForeground(new java.awt.Color(0, 0, 204));
        empInfoForm.setText("EMPLOYEE INFORMATION");
        jPanel3.add(empInfoForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 30));

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 810, 20));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 810, 20));

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1200, 810, 20));

        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 870, 730, 20));

        empPhoneNumValue.setBackground(new java.awt.Color(255, 255, 255));
        empPhoneNumValue.setForeground(new java.awt.Color(0, 0, 0));
        empPhoneNumValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empPhoneNumValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPhoneNumValueActionPerformed(evt);
            }
        });
        jPanel3.add(empPhoneNumValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 190, 30));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 810, 20));

        addressStreet.setBackground(new java.awt.Color(255, 255, 255));
        addressStreet.setForeground(new java.awt.Color(0, 0, 0));
        addressStreet.setText("  Street");
        addressStreet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(addressStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 120, 30));

        addressStreetValue.setBackground(new java.awt.Color(255, 255, 255));
        addressStreetValue.setForeground(new java.awt.Color(0, 0, 0));
        addressStreetValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        addressStreetValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressStreetValueActionPerformed(evt);
            }
        });
        jPanel3.add(addressStreetValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 260, 30));

        addressProvince.setBackground(new java.awt.Color(255, 255, 255));
        addressProvince.setForeground(new java.awt.Color(0, 0, 0));
        addressProvince.setText("  Province");
        addressProvince.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(addressProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 120, 30));

        addressProvinceValue.setBackground(new java.awt.Color(255, 255, 255));
        addressProvinceValue.setForeground(new java.awt.Color(0, 0, 0));
        addressProvinceValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        addressProvinceValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressProvinceValueActionPerformed(evt);
            }
        });
        jPanel3.add(addressProvinceValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 260, 30));

        addressBarangay.setBackground(new java.awt.Color(255, 255, 255));
        addressBarangay.setForeground(new java.awt.Color(0, 0, 0));
        addressBarangay.setText("  Barangay");
        addressBarangay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(addressBarangay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 120, 30));

        addressBarangayValue.setBackground(new java.awt.Color(255, 255, 255));
        addressBarangayValue.setForeground(new java.awt.Color(0, 0, 0));
        addressBarangayValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        addressBarangayValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressBarangayValueActionPerformed(evt);
            }
        });
        jPanel3.add(addressBarangayValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 260, 30));

        addressZipcode.setBackground(new java.awt.Color(255, 255, 255));
        addressZipcode.setForeground(new java.awt.Color(0, 0, 0));
        addressZipcode.setText("  Zipcode");
        addressZipcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(addressZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 120, 30));

        addressZipcodeValue.setBackground(new java.awt.Color(255, 255, 255));
        addressZipcodeValue.setForeground(new java.awt.Color(0, 0, 0));
        addressZipcodeValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        addressZipcodeValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressZipcodeValueActionPerformed(evt);
            }
        });
        jPanel3.add(addressZipcodeValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 260, 30));

        addressCity.setBackground(new java.awt.Color(255, 255, 255));
        addressCity.setForeground(new java.awt.Color(0, 0, 0));
        addressCity.setText("  City");
        addressCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(addressCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 120, 30));

        addressCityValue.setBackground(new java.awt.Color(255, 255, 255));
        addressCityValue.setForeground(new java.awt.Color(0, 0, 0));
        addressCityValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        addressCityValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressCityValueActionPerformed(evt);
            }
        });
        jPanel3.add(addressCityValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 260, 30));

        jScrollPane1.setViewportView(jPanel3);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -8, 860, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void empImmediateSupValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empImmediateSupValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empImmediateSupValueActionPerformed

    private void empLastNameValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empLastNameValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empLastNameValueActionPerformed

    private void empFirstNameValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empFirstNameValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empFirstNameValueActionPerformed

    private void empPersonalEmailValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPersonalEmailValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPersonalEmailValueActionPerformed

    private void empDateHiredValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empDateHiredValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empDateHiredValueActionPerformed

    private void empStatusValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empStatusValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empStatusValueActionPerformed

    private void empPositionValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPositionValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPositionValueActionPerformed

    private void empIDValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIDValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIDValueActionPerformed

    private void empHourlyRateValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empHourlyRateValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empHourlyRateValueActionPerformed

    private void empClothingAllowValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empClothingAllowValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empClothingAllowValueActionPerformed

    private void empGrossSemiValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empGrossSemiValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empGrossSemiValueActionPerformed

    private void empPhilhealthValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPhilhealthValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPhilhealthValueActionPerformed

    private void empRiceSubValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empRiceSubValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empRiceSubValueActionPerformed

    private void empPhoneAllowValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPhoneAllowValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPhoneAllowValueActionPerformed

    private void empBasicSalaryValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empBasicSalaryValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empBasicSalaryValueActionPerformed

    private void empPagIbigValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPagIbigValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPagIbigValueActionPerformed

    private void empSssValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSssValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empSssValueActionPerformed

    private void empTinValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empTinValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empTinValueActionPerformed

    private void empSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSubmitButtonActionPerformed
        EmployeeDao employeeDao = new EmployeeDao();
        Address address = new Address();
        address.setStreet(addressStreetValue.getText());
        address.setBarangay(addressBarangayValue.getText());
        address.setCity(addressCityValue.getText());
        address.setProvince(addressProvinceValue.getText());
        address.setZipcode(addressZipcodeValue.getText());
        user.setAddress(address);
        user.setPhoneNumber(empPhoneNumValue.getText());
        
        //update UI to get province, city, etc.
        boolean isUpdated = employeeDao.save(
                addressStreetValue.getText(), addressBarangayValue.getText(), addressCityValue.getText(),
                addressProvinceValue.getText(), addressZipcodeValue.getText(), 
                empPhoneNumValue.getText(), user.getEmployeeID());
        if(isUpdated){
            empSuccessUpdated.setVisible(true);
            empSubmitButton.setEnabled(false);
            
            Timer timer = new Timer();

            timer.schedule(new TimerTask() {
                @Override
                public void run() {
                    empSuccessUpdated.setVisible(false);
                    empSubmitButton.setEnabled(true);
                }
            }, 3000);
        }
    }//GEN-LAST:event_empSubmitButtonActionPerformed

    private void empRoleValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empRoleValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empRoleValueActionPerformed

    private void empPhoneNumValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPhoneNumValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPhoneNumValueActionPerformed

    private void jScrollPane1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane1MouseWheelMoved
        int rotation = evt.getWheelRotation();
                JScrollBar verticalScrollBar = jScrollPane1.getVerticalScrollBar();
                
                // Control the scroll speed here (higher value = faster scroll)
                int scrollAmount = rotation * 38;  // Adjust this multiplier for smoothness
                
                verticalScrollBar.setValue(verticalScrollBar.getValue() + scrollAmount);
    }//GEN-LAST:event_jScrollPane1MouseWheelMoved

    private void addressStreetValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressStreetValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressStreetValueActionPerformed

    private void addressProvinceValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressProvinceValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressProvinceValueActionPerformed

    private void addressBarangayValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressBarangayValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressBarangayValueActionPerformed

    private void addressZipcodeValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressZipcodeValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressZipcodeValueActionPerformed

    private void addressCityValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressCityValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressCityValueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressBarangay;
    private javax.swing.JTextField addressBarangayValue;
    private javax.swing.JLabel addressCity;
    private javax.swing.JTextField addressCityValue;
    private javax.swing.JLabel addressProvince;
    private javax.swing.JTextField addressProvinceValue;
    private javax.swing.JLabel addressStreet;
    private javax.swing.JTextField addressStreetValue;
    private javax.swing.JLabel addressZipcode;
    private javax.swing.JTextField addressZipcodeValue;
    private javax.swing.JLabel empAddInfo;
    private javax.swing.JLabel empAllow;
    private javax.swing.JLabel empBasicSalary;
    private javax.swing.JTextField empBasicSalaryValue;
    private javax.swing.JLabel empBenefits;
    private javax.swing.JLabel empBirth;
    private com.toedter.calendar.JDateChooser empBirthValue;
    private javax.swing.JLabel empClothingAllow;
    private javax.swing.JTextField empClothingAllowValue;
    private javax.swing.JLabel empContact;
    private javax.swing.JLabel empDateHired;
    private javax.swing.JTextField empDateHiredValue;
    private javax.swing.JLabel empFirstName;
    private javax.swing.JTextField empFirstNameValue;
    private javax.swing.JLabel empGrossSemi;
    private javax.swing.JTextField empGrossSemiValue;
    private javax.swing.JLabel empHourlyRate;
    private javax.swing.JTextField empHourlyRateValue;
    private javax.swing.JLabel empID;
    private javax.swing.JTextField empIDValue;
    private javax.swing.JLabel empImmediateSup;
    private javax.swing.JTextField empImmediateSupValue;
    private javax.swing.JLabel empInfoForm;
    private javax.swing.JLabel empLastName;
    private javax.swing.JTextField empLastNameValue;
    private javax.swing.JLabel empPagIbig;
    private javax.swing.JTextField empPagIbigValue;
    private javax.swing.JLabel empPayInfo;
    private javax.swing.JLabel empPersonalEmail;
    private javax.swing.JTextField empPersonalEmailValue;
    private javax.swing.JLabel empPhilhealth;
    private javax.swing.JTextField empPhilhealthValue;
    private javax.swing.JLabel empPhoneAllow;
    private javax.swing.JTextField empPhoneAllowValue;
    private javax.swing.JLabel empPhoneNum;
    private javax.swing.JTextField empPhoneNumValue;
    private javax.swing.JLabel empPosition;
    private javax.swing.JTextField empPositionValue;
    private javax.swing.JLabel empRiceSub;
    private javax.swing.JTextField empRiceSubValue;
    private javax.swing.JComboBox<String> empRoleValue;
    private javax.swing.JLabel empSalary;
    private javax.swing.JLabel empSss;
    private javax.swing.JTextField empSssValue;
    private javax.swing.JLabel empStatus;
    private javax.swing.JTextField empStatusValue;
    private javax.swing.JButton empSubmitButton;
    private javax.swing.JLabel empSuccessUpdated;
    private javax.swing.JLabel empTin;
    private javax.swing.JTextField empTinValue;
    private javax.swing.JLabel empUserRole;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
