/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import models.AccountAccess;
import models.HRPersonnel;
import models.Employee;
import models.Payroll;
import models.Deductions;
import models.Benefits;
import alex.oopmotorphpayrollsystem.PayrollSummaryExcel;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.File;
import javax.swing.JScrollBar;

/**
 *
 * @author Alex Resurreccion
 */
public class SummaryReport extends javax.swing.JPanel {
    private AccountAccess account;
    private HRPersonnel user; 
    List<Payroll> payrollList;
    /**
     * Creates new form SummaryReport
     */
    public SummaryReport() {
        initComponents();
    }
    
    public SummaryReport(AccountAccess account, HRPersonnel user) {
        this.account = account;
        this.user = user;
        initComponents();
//        populateWeekComboBox();
        loadPayrollData();
    }
    
    private void loadPayrollData(){
        this.payrollList = user.loadSummaryReport(
                filterMonthlyvalue.getMonth() + 1, filterMonthlyYearValue.getYear());
        DefaultTableModel model = (DefaultTableModel) payrollReportTable.getModel();
        model.setRowCount(0);
        boolean hasPending = false;
        for (Payroll payroll : payrollList) {
            Employee emp = payroll.getEmployee();
            Deductions deduct = payroll.getDeductions();
            Benefits benefit = emp.getBenefits();
            Object data[] = {
                emp.getEmployeeID(),
                emp.getFirstName() + " " + emp.getLastName(),
                emp.getPosition(),
                payroll.getGrossIncome(),
                deduct.calculateTotalDeductions(),
                benefit.calculateTotalAllowance(),
                payroll.getNetPay(),
            };

            // Add the row to the table model
            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        payrollReportTable = new javax.swing.JTable();
        payrollReport = new javax.swing.JLabel();
        downloadSummary = new javax.swing.JButton();
        filterMonthly = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        filterMonthlyvalue = new com.toedter.calendar.JMonthChooser();
        year = new javax.swing.JLabel();
        filterMonthlyYearValue = new com.toedter.calendar.JYearChooser();
        search = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane9.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane9MouseWheelMoved(evt);
            }
        });

        payrollReportTable.setAutoCreateRowSorter(true);
        payrollReportTable.setBackground(new java.awt.Color(255, 255, 255));
        payrollReportTable.setForeground(new java.awt.Color(0, 0, 0));
        payrollReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"10001", "Manuel III A.", "Executive", "53,500.00", "4,500.00", "5,000.00", "54,000.00"},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "EMPLOYEE  ID", "EMPLOYEE NAME", "POSITION", "GROSS INCOME", "TOTAL DEDUCTIONS", "TOTAL BENEFITS", "NET PAY"
            }
        ));
        payrollReportTable.setGridColor(new java.awt.Color(102, 102, 102));
        payrollReportTable.setSelectionBackground(new java.awt.Color(0, 0, 153));
        payrollReportTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        payrollReportTable.setShowGrid(true);
        jScrollPane9.setViewportView(payrollReportTable);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 860, 460));

        payrollReport.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        payrollReport.setForeground(new java.awt.Color(0, 0, 204));
        payrollReport.setText("Reports");
        jPanel1.add(payrollReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, -1));

        downloadSummary.setBackground(new java.awt.Color(255, 255, 255));
        downloadSummary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        downloadSummary.setForeground(new java.awt.Color(0, 0, 204));
        downloadSummary.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alex Resurreccion\\Documents\\NetBeansProjects\\OOPMotorPhPayrollSystem\\resources\\download (1).png")); // NOI18N
        downloadSummary.setText("Download Summary Report");
        downloadSummary.setBorder(null);
        downloadSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadSummaryActionPerformed(evt);
            }
        });
        jPanel1.add(downloadSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 220, 50));

        filterMonthly.setBackground(new java.awt.Color(255, 255, 255));
        filterMonthly.setForeground(new java.awt.Color(0, 0, 0));
        filterMonthly.setText("Filter monthly report");
        filterMonthly.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(filterMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 30));

        month.setBackground(new java.awt.Color(255, 255, 255));
        month.setForeground(new java.awt.Color(0, 0, 0));
        month.setText("Month");
        jPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        filterMonthlyvalue.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(filterMonthlyvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 30));

        year.setBackground(new java.awt.Color(255, 255, 255));
        year.setForeground(new java.awt.Color(0, 0, 0));
        year.setText("Year");
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        filterMonthlyYearValue.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(filterMonthlyYearValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 70, 30));

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alex Resurreccion\\Documents\\NetBeansProjects\\OOPMotorPhPayrollSystem\\resources\\searchIcon.png")); // NOI18N
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        search.setFocusPainted(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        loadPayrollData();
        
    }//GEN-LAST:event_searchActionPerformed

    private void downloadSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadSummaryActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Payroll Report");
        fileChooser.setSelectedFile(new File("Payroll_Report.xlsx")); // Default name

        int userSelection = fileChooser.showSaveDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            PayrollSummaryExcel.generatePayrollReport(this.payrollList, fileToSave);
        }
    }//GEN-LAST:event_downloadSummaryActionPerformed

    private void jScrollPane9MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane9MouseWheelMoved
        int rotation = evt.getWheelRotation();
                JScrollBar verticalScrollBar = jScrollPane9.getVerticalScrollBar();
                
                // Control the scroll speed here (higher value = faster scroll)
                int scrollAmount = rotation * 38;  // Adjust this multiplier for smoothness
                
                verticalScrollBar.setValue(verticalScrollBar.getValue() + scrollAmount);
    }//GEN-LAST:event_jScrollPane9MouseWheelMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton downloadSummary;
    private javax.swing.JLabel filterMonthly;
    private com.toedter.calendar.JYearChooser filterMonthlyYearValue;
    private com.toedter.calendar.JMonthChooser filterMonthlyvalue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel month;
    private javax.swing.JLabel payrollReport;
    private javax.swing.JTable payrollReportTable;
    private javax.swing.JButton search;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
